### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by lph656** [thinwayliu/FLBA-Backdoor#2]
In the file ./core/model/metric/proto_net.py, the following line of code is used:
support_img[i:i + self.shot_num, :, -6:, -6:] += self.trigger_list[trigger_index]
However, the attribute self.trigger_list is not defined anywhere in the entire project.

**Comment by thinwayliu** [comment]
Sorry for the misunderstanding, there were some problems with our previous readme and code, we fixed them quickly. _**set_forward_test**_ is a useless function. training and validation of FLBA backdoors are contained in the _function **set_forward_ours**_.

**Comment by lph656** [comment]
I sincerely appreciate your assistance in resolving the issues, which has been of great help to me. After reviewing the corrected source code, I still have some questions and would like to kindly seek your guidance to confirm if my understanding is correct.

(1) In _baseline_plus.py_, should **output, acc, asr = self.model.set_forward_loss(batch)** be modified to **output, acc, asr = self.model.set_forward_ours(batch)** to ensure that the return values match the received values?
(2) Later, when running the command _python run_test_FLBA.py_, an error occurs. After analyzing the source code, I found that the batch sample size was set incorrectly. Should we either:
Change **"test_shot": 1** to **"test_shot": 5** in _run_test_FLBA.py_, or
Change **num = 5** to **num = 1** in _baseline_plus.py_?
This is to ensure that the batch sample size is consistent, and the division of target and untarget class samples is correct.

**Comment by thinwayliu** [comment]
1. self.model.set_forward_loss is used for normal clean training and tested, output, acc, asr = self.model.set_forward_ours(batch) is used for FLBA poisoning and tested, both of them get output. Here self.model.set_forward_xxx represents different xxx backdoor attack methods.
2. you are right that it is supposed to be consistent. The error here is most likely due to the changes I made to the SHOT NUMBER while doing the ablation experiment.
